language: android

before_install:
- yes | sdkmanager "platforms;android-28"
- sudo apt-get install jq
- (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses

android:
  components:
  - build-tools-28.0.1
  - android-28
  licenses:
  - 'android-sdk-license-.+'


jdk:
- oraclejdk8

jobs:
  include:
  # compile build
  - stage: compile
    language: android
    script: ./gradlew androidDependencies
  # test run section
  - stage: All Tests
    language: android
    before_script: chmod +x gradlew
    script: ./gradlew testDevDebug
  # Run Lint Tests
  - stage: Lint Tests
    language: android
    before_script: chmod +x gradlew
    script: ./gradlew lint --no-daemon -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy="in-process" -Dorg.gradle.jvmargs=-Xmx4096M